// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TiendaChurrascosApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721090130_BaseEstructura")]
    partial class BaseEstructura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("TiendaChurrascosApi.Models.Churrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComboId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Guarniciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Porciones")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Termino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.ToTable("Churrascos");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.DulceTipico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja12")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja24")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja6")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.ToTable("Dulces");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.Churrasco", b =>
                {
                    b.HasOne("TiendaChurrascosApi.Models.Combo", null)
                        .WithMany("Churrascos")
                        .HasForeignKey("ComboId");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.DulceTipico", b =>
                {
                    b.HasOne("TiendaChurrascosApi.Models.Combo", null)
                        .WithMany("Dulces")
                        .HasForeignKey("ComboId");
                });

            modelBuilder.Entity("TiendaChurrascosApi.Models.Combo", b =>
                {
                    b.Navigation("Churrascos");

                    b.Navigation("Dulces");
                });
#pragma warning restore 612, 618
        }
    }
}
