// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TiendaChurrascosApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721085606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("TiendaChurrascosApi.Models.Churrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Guarniciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Porciones")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Termino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Churrascos");
                });
#pragma warning restore 612, 618
        }
    }
}
