// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TiendaChurrascosApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721150612_UpdateSchemaFull")]
    partial class UpdateSchemaFull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Churrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Porciones")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Termino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrecio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Churrascos");
                });

            modelBuilder.Entity("ChurrascoGuarnicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChurrascoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsExtra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuarnicionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChurrascoId");

                    b.HasIndex("GuarnicionId");

                    b.ToTable("ChurrascoGuarnicion");
                });

            modelBuilder.Entity("Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("ComboChurrasco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChurrascoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChurrascoId");

                    b.HasIndex("ComboId");

                    b.ToTable("ComboChurrasco");
                });

            modelBuilder.Entity("ComboDulce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DulceTipicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TamañoCaja")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("DulceTipicoId");

                    b.ToTable("ComboDulce");
                });

            modelBuilder.Entity("DulceTipico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja12")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja24")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCaja6")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dulces");
                });

            modelBuilder.Entity("Guarnicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guarnicion");
                });

            modelBuilder.Entity("Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("ChurrascoGuarnicion", b =>
                {
                    b.HasOne("Churrasco", "Churrasco")
                        .WithMany("Guarniciones")
                        .HasForeignKey("ChurrascoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guarnicion", "Guarnicion")
                        .WithMany("Churrascos")
                        .HasForeignKey("GuarnicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Churrasco");

                    b.Navigation("Guarnicion");
                });

            modelBuilder.Entity("ComboChurrasco", b =>
                {
                    b.HasOne("Churrasco", "Churrasco")
                        .WithMany()
                        .HasForeignKey("ChurrascoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Combo", "Combo")
                        .WithMany("Churrascos")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Churrasco");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("ComboDulce", b =>
                {
                    b.HasOne("Combo", "Combo")
                        .WithMany("Dulces")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DulceTipico", "DulceTipico")
                        .WithMany()
                        .HasForeignKey("DulceTipicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("DulceTipico");
                });

            modelBuilder.Entity("Churrasco", b =>
                {
                    b.Navigation("Guarniciones");
                });

            modelBuilder.Entity("Combo", b =>
                {
                    b.Navigation("Churrascos");

                    b.Navigation("Dulces");
                });

            modelBuilder.Entity("Guarnicion", b =>
                {
                    b.Navigation("Churrascos");
                });
#pragma warning restore 612, 618
        }
    }
}
